# Generated by Django 2.0.9 on 2019-01-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0002_auto_20190105_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelesscount',
            name='number_in_seattle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_asian',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_black',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_female',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_gnc',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_hawaiian_api',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_indigenous',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_latino',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_male',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_multiracial',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_trans',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='pct_white',
            field=models.IntegerField(null=True),
        ),
    ]
