# Generated by Django 2.0.9 on 2019-01-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0003_auto_20190107_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowIncomeHousing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_units', models.IntegerField()),
                ('year_placed_in_service', models.IntegerField()),
                ('name', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('zip_code', models.TextField(null=True)),
                ('council_district', models.IntegerField(null=True)),
                ('hud', models.NullBooleanField()),
                ('sha', models.NullBooleanField()),
                ('state_or_county', models.NullBooleanField()),
                ('wshfc', models.NullBooleanField()),
                ('city_of_seattle', models.NullBooleanField()),
            ],
        ),
    ]
