# Generated by Django 2.0.9 on 2019-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0004_lowincomehousing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPermits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.TextField()),
                ('permit_class', models.TextField()),
                ('permit_class_mapped', models.TextField()),
                ('permit_type', models.TextField(null=True)),
                ('permit_type_mapped', models.TextField()),
                ('description', models.TextField(null=True)),
                ('number_of_units', models.IntegerField(null=True)),
                ('housing_units_removed', models.IntegerField(null=True)),
                ('housing_units_added', models.IntegerField(null=True)),
                ('permit_application_date', models.TextField(null=True)),
                ('permit_approval_date', models.TextField(null=True)),
                ('permit_completion_date', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
            ],
        ),
    ]
