# Generated by Django 2.0.9 on 2019-01-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0005_buildingpermits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingPermits',
            new_name='BuildingPermit',
        ),
    ]
