# Generated by Django 2.0.9 on 2019-01-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0006_auto_20190108_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncampmentRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('year', models.TextField()),
                ('location', models.TextField()),
                ('departments_responsible_for_removal', models.TextField(null=True)),
                ('vehicle_hazard', models.NullBooleanField()),
                ('criminal_activity', models.NullBooleanField()),
                ('waste_and_debris', models.NullBooleanField()),
                ('health_hazard_to_neighborhood', models.NullBooleanField()),
                ('limited_emergency_services', models.NullBooleanField()),
                ('scheduled_worksite', models.NullBooleanField()),
                ('damage_to_environment', models.NullBooleanField()),
                ('proximity_to_school_or_elderly', models.NullBooleanField()),
            ],
        ),
    ]
