# Generated by Django 2.0.9 on 2019-01-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0007_encampmentremoval'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFTEProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField()),
                ('tax_exemption_start', models.IntegerField()),
                ('tax_exemption_end', models.IntegerField()),
                ('year_of_approval', models.IntegerField(null=True)),
                ('address', models.TextField()),
                ('council_district', models.IntegerField(null=True)),
                ('targeted_area', models.TextField(null=True)),
                ('subsidized', models.NullBooleanField()),
                ('total_units', models.IntegerField(null=True)),
                ('total_affordable_units', models.IntegerField(null=True)),
                ('microhousing', models.NullBooleanField()),
                ('SEDU_total', models.IntegerField(null=True)),
                ('SEDU_affordable', models.IntegerField(null=True)),
                ('studio_units_total', models.IntegerField(null=True)),
                ('studio_units_affordable', models.IntegerField(null=True)),
                ('one_br_total', models.IntegerField(null=True)),
                ('one_br_affordable', models.IntegerField(null=True)),
                ('two_br_total', models.IntegerField(null=True)),
                ('two_br_affordable', models.IntegerField(null=True)),
                ('three_br_total', models.IntegerField(null=True)),
                ('three_br_affordable', models.IntegerField(null=True)),
                ('four_br_total', models.IntegerField(null=True)),
                ('four_br_affordable', models.IntegerField(null=True)),
            ],
        ),
    ]
