# Generated by Django 2.0.9 on 2019-01-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0008_mfteprojects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MFTEProjects',
            new_name='MFTEProject',
        ),
    ]
