# Generated by Django 2.0.9 on 2019-01-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0009_auto_20190109_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_population', models.IntegerField()),
                ('gini_index', models.FloatField()),
                ('median_income', models.IntegerField()),
                ('income_under_10000', models.IntegerField(null=True)),
                ('income_10000_14999', models.IntegerField(null=True)),
                ('income_15000_19999', models.IntegerField(null=True)),
                ('income_20000_24999', models.IntegerField(null=True)),
                ('income_25000_29999', models.IntegerField(null=True)),
                ('income_30000_34999', models.IntegerField(null=True)),
                ('income_35000_39999', models.IntegerField(null=True)),
                ('income_40000_44999', models.IntegerField(null=True)),
                ('income_45000_49999', models.IntegerField(null=True)),
                ('income_50000_59999', models.IntegerField(null=True)),
                ('income_60000_74999', models.IntegerField(null=True)),
                ('income_75000_99999', models.IntegerField(null=True)),
                ('income_100000_124999', models.IntegerField(null=True)),
                ('income_125000_149999', models.IntegerField(null=True)),
                ('income_150000_199999', models.IntegerField(null=True)),
                ('income_over_200000', models.IntegerField(null=True)),
                ('median_rent_studio', models.IntegerField(null=True)),
                ('median_rent_1br', models.IntegerField(null=True)),
                ('median_rent_2br', models.IntegerField(null=True)),
                ('median_rent_3br', models.IntegerField(null=True)),
                ('median_rent_4br', models.IntegerField(null=True)),
                ('median_rent_5br', models.IntegerField(null=True)),
            ],
        ),
    ]
