# Generated by Django 2.0.9 on 2019-01-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0010_communitysurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField()),
                ('service', models.TextField(null=True)),
                ('department', models.TextField(null=True)),
                ('program', models.TextField(null=True)),
                ('expense_category', models.TextField(null=True)),
                ('expense_type', models.TextField(null=True)),
                ('fund', models.TextField(null=True)),
                ('fund_type', models.TextField(null=True)),
                ('description', models.TextField()),
                ('recommended_amount', models.TextField(null=True)),
                ('approved_amount', models.TextField()),
            ],
        ),
    ]
