# Generated by Django 2.0.9 on 2019-01-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0011_citybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.TextField()),
                ('median_sale_price', models.TextField()),
                ('homes_sold', models.TextField(null=True)),
                ('days_on_market', models.IntegerField()),
            ],
        ),
    ]
