# Generated by Django 2.0.9 on 2019-01-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0012_housingmarket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfteproject',
            name='tax_exemption_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mfteproject',
            name='tax_exemption_start',
            field=models.IntegerField(null=True),
        ),
    ]
