# Generated by Django 2.0.9 on 2019-01-15 19:46

from django.db import migrations
import requests
from requests.auth import HTTPDigestAuth
import json
import environ

env = environ.Env(DEBUG=(bool, False),)
environ.Env.read_env()

YEARS = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]

URL_2010_to_2014 = "https://api.census.gov/data/2010/acs/acs1?get=B01003_001E,B19083_001E,B19013_001E,B19001_002E,B19001_003E,B19001_004E,B19001_005E,B19001_006E,B19001_007E,B19001_008E,B19001_009E,B19001_010E,B19001_011E,B19001_012E,B19001_013E,B19001_014E,B19001_015E,B19001_016E,B19001_017E,NAME&for=county:033&in=state:53&key="

URL_POST_2014 = "https://api.census.gov/data/2014/acs/acs1?get=B01003_001E,B19083_001E,B19013_001E,B19001_002E,B19001_003E,B19001_004E,B19001_005E,B19001_006E,B19001_007E,B19001_008E,B19001_009E,B19001_010E,B19001_011E,B19001_012E,B19001_013E,B19001_014E,B19001_015E,B19001_016E,B19001_017E,B25031_002E,B25031_003E,B25031_004E,B25031_005E,B25031_006E,B25031_007E,NAME&for=county:033&in=state:53&key="

def populate_community_surveys(apps, schema_editor):
    CommunitySurvey = apps.get_model('seattlizationAPI', 'CommunitySurvey')

    for year in YEARS:
        if year <= 2014:
            myResponse = requests.get(URL_2010_to_2014 + env('US_CENSUS_BUREAU_KEY'))
            #print (myResponse.status_code)
            #For successful API call, response code will be 200 (OK)
            if(myResponse.ok):
                # Loading the response data into a dict variable
                # json.loads takes in only binary or string variables so using content to fetch binary content
                # Loads (Load String) takes a Json file and converts into python data structure (dict or list, depending on JSON)
                jData = json.loads(myResponse.content)
                print("The response contains {0} properties".format(len(jData)))
                print("\n")
                for key in jData:
                    print (key + " : " + jData[key])
            else:
              # If response code is not ok (200), print the resulting http error code with description
                myResponse.raise_for_status()
    else:
        myResponse = requests.get(URL_POST_2014 + env('US_CENSUS_BUREAU_KEY'))

        if(myResponse.ok):
            jData = json.loads(myResponse.content)
            print("The response contains {0} properties".format(len(jData)))
            print("\n")
            for key in jData:
                print (key + " : " + jData[key])
        else:
            myResponse.raise_for_status()

class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0012_housingmarket'),
    ]

    operations = [
        migrations.RunPython(populate_community_surveys),
    ]
