# Generated by Django 2.0.9 on 2019-01-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0013_auto_20190117_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='encampmentremoval',
            name='found_on_city_property',
            field=models.NullBooleanField(),
        ),
    ]
