# Generated by Django 2.0.9 on 2019-01-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0014_encampmentremoval_found_on_city_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='encampmentremoval',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
