# Generated by Django 2.0.9 on 2019-01-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0015_encampmentremoval_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingmarket',
            name='days_on_market',
        ),
        migrations.RemoveField(
            model_name='housingmarket',
            name='month',
        ),
        migrations.RemoveField(
            model_name='housingmarket',
            name='year',
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='avg_days_on_market',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='number_of_new_listings',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='number_of_pending_sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='pct_sold_above_list',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='period_begin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='period_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='housingmarket',
            name='homes_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='housingmarket',
            name='median_sale_price',
            field=models.TextField(null=True),
        ),
    ]
