# Generated by Django 2.0.9 on 2019-01-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0016_auto_20190118_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingmarket',
            name='period_begin',
        ),
        migrations.RemoveField(
            model_name='housingmarket',
            name='period_end',
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='month',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='housingmarket',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
