# Generated by Django 2.0.9 on 2019-01-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0017_auto_20190118_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingmarket',
            name='pct_sold_above_list',
            field=models.TextField(null=True),
        ),
    ]
