# Generated by Django 2.0.9 on 2019-01-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0018_auto_20190118_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encampmentremoval',
            old_name='criminal_activity',
            new_name='criminal_activity_beyond_drug_use',
        ),
    ]
