# Generated by Django 2.0.9 on 2019-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0019_auto_20190118_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelesscount',
            name='number_in_shelter_and_transitional_housing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='emergency_shelter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='number_in_seattle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_asian',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_black',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_gnc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_hawaiian_api',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_indigenous',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_latino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_multiracial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_trans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='pct_white',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='transitional_housing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homelesscount',
            name='unsheltered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
