# Generated by Django 2.0.9 on 2019-01-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0020_auto_20190118_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelesscount',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
