# Generated by Django 2.0.9 on 2019-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0021_auto_20190118_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelesscount',
            old_name='number_in_seattle',
            new_name='number_unsheltered_in_seattle',
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='number_female_unsheltered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='number_male_unsheltered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='number_of_minors_unsheltered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homelesscount',
            name='number_unknown_gender_unsheltered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
