# Generated by Django 2.0.9 on 2019-01-18 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0022_auto_20190118_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homelesscount',
            old_name='number_female_unsheltered',
            new_name='number_female_on_street',
        ),
        migrations.RenameField(
            model_name='homelesscount',
            old_name='number_male_unsheltered',
            new_name='number_male_on_street',
        ),
        migrations.RenameField(
            model_name='homelesscount',
            old_name='number_of_minors_unsheltered',
            new_name='number_of_minors_on_street',
        ),
        migrations.RenameField(
            model_name='homelesscount',
            old_name='number_unknown_gender_unsheltered',
            new_name='number_unknown_gender_on_street',
        ),
    ]
