# Generated by Django 2.0.9 on 2019-01-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seattlizationAPI', '0023_auto_20190118_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelesscount',
            name='number_sheltered_in_seattle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
